update image name

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,8 +48,15 @@ jobs:
           kubectl-version: "v1.21.13"
       - run:
           name: "Creating cluster"
-          command: |                   
-            eksctl create cluster --name ${EKS_CLUSTER_NAME} --nodes 3 --nodes-min 1 --nodes-max 5 --region ${AWS_DEFAULT_REGION}          
+          command: |
+            echo 'Pre-check before creating...'
+            aws eks describe-cluster --name ${EKS_CLUSTER_NAME}
+            if [ $? -ne 0 ]; then
+              echo 'Cluster not found. Creating new cluster...'
+              eksctl create cluster --name ${EKS_CLUSTER_NAME} --nodes 3 --nodes-min 1 --nodes-max 5 --region ${AWS_REGION}
+            else
+              echo 'Cluster existed. Skiping...'
+            fi
 
   k8s-deployment:
     executor: docker-ex
